### ISSUE TITLE
pypy3 stat issue

### ISSUE THREAD

**Issue by ThomasWaldmann** [benhoyt/scandir#117]
Been trying scandir tests on travis-ci with pypy3:
```
        - python: pypy3
          os: linux
          dist: trusty
          env: TOXENV=pypy3
```

I've seen this issue:
```
$ python --version
Python 3.5.3 (a39af0be3a22, Jun 05 2017, 20:18:00)
[PyPy 5.8.0-beta0 with GCC 6.2.0 20160901]
...
======================================================================
ERROR: test_bytes (test_scandir.TestScandirC)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/benhoyt/scandir/test/test_scandir.py", line 210, in test_bytes
    entries = [e for e in self.scandir_func(path) if e.name.startswith(b'unicod')]
FileNotFoundError: [Errno 2] No such file or directory: b'/home/travis/build/benhoyt/scandir/test/testdir/subdir'
======================================================================
ERROR: test_symlink (test_scandir.TestScandirC)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/benhoyt/scandir/test/test_scandir.py", line 186, in test_symlink
    for e in entries],
  File "/home/travis/build/benhoyt/scandir/test/test_scandir.py", line 186, in <listcomp>
    for e in entries],
TypeError: DirEntry.stat() argument 1 must be impossible<bad format char>, not bool
----------------------------------------------------------------------
Ran 44 tests in 0.041s
FAILED (errors=2, skipped=4)
```

**Comment by ThomasWaldmann** [comment]
Considering this comment, this maybe was already fixed in a more recent pypy3 release:

https://github.com/benhoyt/scandir/issues/80#issuecomment-465135726

Note:
The above result was from pypy3 on trusty. I also tried pypy3 on xenial and just got a "403 Access denied" from travis when trying to DL the pypy3.tgz.

**Comment by benhoyt** [comment]
Going to close this on the assumption this is fixed (given the above comment). Feel free to re-open if not.
