### ISSUE TITLE
Test failures in OpenBSD.

### ISSUE THREAD

**Issue by dumol** [benhoyt/scandir#79]
OpenBSD 6.0
Python 2.7.11
scandir 1.5
LC_ALL exported as en_US.UTF-8 to avoid https://github.com/benhoyt/scandir/issues/78

Results:
```
test_basic (test_scandir.TestScandirC) ... ok
test_bytes (test_scandir.TestScandirC) ... ok
test_dir_entry (test_scandir.TestScandirC) ... ok
test_file_attributes (test_scandir.TestScandirC) ... skipped 'st_file_attributes not supported'
test_path (test_scandir.TestScandirC) ... ok
test_returns_iter (test_scandir.TestScandirC) ... ok
test_stat (test_scandir.TestScandirC) ... ok
test_symlink (test_scandir.TestScandirC) ... ok
test_unicode (test_scandir.TestScandirC) ... ok
test_walk_unicode_handling (test_scandir.TestScandirC) ... ok
test_basic (test_scandir.TestScandirGeneric) ... ok
test_bytes (test_scandir.TestScandirGeneric) ... ok
test_dir_entry (test_scandir.TestScandirGeneric) ... ok
test_file_attributes (test_scandir.TestScandirGeneric) ... skipped 'st_file_attributes not supported'
test_path (test_scandir.TestScandirGeneric) ... ok
test_returns_iter (test_scandir.TestScandirGeneric) ... ok
test_stat (test_scandir.TestScandirGeneric) ... ok
test_symlink (test_scandir.TestScandirGeneric) ... ok
test_unicode (test_scandir.TestScandirGeneric) ... ok
test_walk_unicode_handling (test_scandir.TestScandirGeneric) ... ok
test_basic (test_scandir.TestScandirPython) ... FAIL
test_bytes (test_scandir.TestScandirPython) ... FAIL
test_dir_entry (test_scandir.TestScandirPython) ... ERROR
test_file_attributes (test_scandir.TestScandirPython) ... skipped 'st_file_attributes not supported'
test_path (test_scandir.TestScandirPython) ... FAIL
test_returns_iter (test_scandir.TestScandirPython) ... ok
test_stat (test_scandir.TestScandirPython) ... ERROR
test_symlink (test_scandir.TestScandirPython) ... FAIL
test_unicode (test_scandir.TestScandirPython) ... FAIL
test_walk_unicode_handling (test_scandir.TestScandirPython) ... ok
test_traversal (test_walk.TestWalk) ... ok
test_symlink_to_directory (test_walk.TestWalkSymlink) ... ok
test_symlink_to_file (test_walk.TestWalkSymlink) ... ok

======================================================================
ERROR: test_dir_entry (test_scandir.TestScandirPython)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildslave/runtime/build-openbsd60-x64/slave/python-package-obsd-60/build/python-modules/python-scandir-1.5/test/test_scandir.py", line 120, in test_dir_entry
    e = entries['file1.txt']
KeyError: u'file1.txt'

======================================================================
ERROR: test_stat (test_scandir.TestScandirPython)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildslave/runtime/build-openbsd60-x64/slave/python-package-obsd-60/build/python-modules/python-scandir-1.5/test/test_scandir.py", line 133, in test_stat
    os_stat = os.stat(os.path.join(TEST_PATH, entry.name))
OSError: [Errno 2] No such file or directory: '/home/buildslave/runtime/build-openbsd60-x64/slave/python-package-obsd-60/build/python-modules/python-scandir-1.5/test/testdir/\x0c'

======================================================================
FAIL: test_basic (test_scandir.TestScandirPython)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildslave/runtime/build-openbsd60-x64/slave/python-package-obsd-60/build/python-modules/python-scandir-1.5/test/test_scandir.py", line 114, in test_basic
    ('linkdir', True), ('subdir', True)])
AssertionError: Lists differ: [(u'', True), (u'\x0c', False)... != [(u'file1.txt', False), (u'fil...

First differing element 0:
(u'', True)
(u'file1.txt', False)

First list contains 2 additional elements.
First extra element 4:
(u'<', False)

+ [(u'file1.txt', False),
+  (u'file2.txt', False),
+  (u'linkdir', True),
+  (u'subdir', True)]
- [(u'', True),
-  (u'\x0c', False),
-  (u'\x18', False),
-  (u'(', False),
-  (u'<', False),
-  (u'P', False)]

======================================================================
FAIL: test_bytes (test_scandir.TestScandirPython)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildslave/runtime/build-openbsd60-x64/slave/python-package-obsd-60/build/python-modules/python-scandir-1.5/test/test_scandir.py", line 217, in test_bytes
    self.assertEqual(len(entries), 1)
AssertionError: 0 != 1

======================================================================
FAIL: test_path (test_scandir.TestScandirPython)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildslave/runtime/build-openbsd60-x64/slave/python-package-obsd-60/build/python-modules/python-scandir-1.5/test/test_scandir.py", line 177, in test_path
    ['file1.txt', 'file2.txt', 'linkdir', 'subdir'])
AssertionError: Lists differ: [u'', u'\x0c', u'\x18', u'(', ... != [u'file1.txt', u'file2.txt', u...

First differing element 0:

file1.txt

First list contains 2 additional elements.
First extra element 4:
<

- [u'', u'\x0c', u'\x18', u'(', u'<', u'P']
+ [u'file1.txt', u'file2.txt', u'linkdir', u'subdir']

======================================================================
FAIL: test_symlink (test_scandir.TestScandirPython)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildslave/runtime/build-openbsd60-x64/slave/python-package-obsd-60/build/python-modules/python-scandir-1.5/test/test_scandir.py", line 192, in test_symlink
    ('linksubdir', False)])
AssertionError: Lists differ: [(u'', False), (u'\x0c', False... != [(u'file1.txt', False), (u'lin...

First differing element 0:
(u'', False)
(u'file1.txt', False)

First list contains 2 additional elements.
First extra element 4:
(u'@', False)

- [(u'', False),
+ [(u'file1.txt', False),
?     +++++++++

+  (u'link_to_dir', True),
+  (u'link_to_file', True),
+  (u'linksubdir', False)]
-  (u'\x0c', False),
-  (u'\x18', False),
-  (u',', False),
-  (u'@', False),
-  (u'X', False)]

======================================================================
FAIL: test_unicode (test_scandir.TestScandirPython)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildslave/runtime/build-openbsd60-x64/slave/python-package-obsd-60/build/python-modules/python-scandir-1.5/test/test_scandir.py", line 235, in test_unicode
    self.assertEqual(len(entries), 1)
AssertionError: 0 != 1

----------------------------------------------------------------------
Ran 33 tests in 0.065s

FAILED (failures=5, errors=2, skipped=3)
```

**Comment by pkorovin** [comment]
I have the same problem with OpenBSD-CURRENT/amd64. Setting LANG/LC_ALL to en_US.UTF-8 didn't help.

**Comment by benhoyt** [comment]
Do you (or someone with access to a BSD system) have a suggested fix or know what the underlying issue is here?

**Comment by ofek** [comment]
@benhoyt Fixed in #109 ?

**Comment by benhoyt** [comment]
Ah yes, looks like it -- thanks!

**Comment by dumol** [comment]
Confirmed in our environment as well. Thanks!
